# fly.toml file for FAFIFA KUE backend

app = "fafifa-kue-backend"

primary_region = "sin"

[env]
PORT = "8080"
POSTGRES_URL = "postgresql://postgres:Filekerjaku88.@db.vqnpwkyehzjddsoxfgsf.supabase.co:5432/postgres"
DEBUG = "true"
API_VERSION = "v1"

[experimental]
auto_rollback = true

[[services]]
internal_port = 8080
protocol = "tcp"

[[services.ports]]
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443
    